[build]
publish = "public"
command = "hugo --gc --minify -d public;"

[context.production.environment]
HUGO_VERSION = "0.79.1"

[context.branch-deploy]
command = "hugo --minify --gc -d public -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.79.1"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.79.1"


[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404


[[redirects]]
  from = "https://x.netlify.app/"
  to = "https://www.domain.com/"
  status = 301
  force = true #COMMENT: ensure that we always redirect


[[headers]]
for = "/*.jpg"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/webfonts/*"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*"

[headers.values]
# We don't use iframes. Block them.
X-Frame-Options = "DENY"
# Don't allow Mime-sniffing.
X-Content-Type-Options = "nosniff"
# Add reflective XSS protection.
X-XSS-Protection = "1; mode=block"
# Force HTTPS only.
Strict-Transport-Security = "max-age=31536000; includeSubDomains"
# Load scripts only via HTTPS and from allowed domains.
# Content-Security-Policy = "default-src *; script-src *; script-src-elem *; script-src-attr *; style-src *; style-src-elem *; style-src-attr *; img-src *; font-src *; connect-src *; media-src *; object-src *; prefetch-src *"
# Only send referred when HTTPS is used.
Referrer-Policy = "strict-origin-when-cross-origin"
# Disable certain magic features, lol.


