backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: static/img
public_folder: /img
collections:
  - label: "Settings"
    name: "settings"
    files:
      - name: "config"
        label: "Master Config File"
        file: "config.toml"
        fields:
          - { label: 'BaseURL', name: 'baseURL', widget: 'string', default: "/" }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: "Language Code", name: "languageCode", widget: "string"}
          - { label: "DefaultContentLanguage", name: "DefaultContentLanguage", widget: "hidden"}
          - { label: "disableKinds", name: "disabledKinds", widget: "hidden"}
          - { label: "sitemap", name: "sitemap", widget: "hidden"}
          - { label: "build", name: "build", widget: "hidden"}
          - { label: "enableRobotsTXT", name: "enableRobotsTXT", widget: "hidden"}
          
          - label: "Menu"
            name: "menu"
            widget: "object"
            fields:
              - label: 'Menu Items'
                name: 'main'
                widget: list
                fields:
                  - { label: 'Name', name: 'name', widget: 'string' }
                  - { label: 'URL', name: 'url', widget: 'string' }
                  - { label: 'Weight', name: 'weight', widget: 'string' }
          - label: "Parameters"
            name: "params"
            widget: "object"
            fields:
              - { label: 'Site Name', name: 'sitename', widget: 'string' }
              - { label: 'Service Name', name: 'servicename', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }
              - { label: "Video On Website", name: "videoOn", widget: "boolean", required: false }
              - { label: 'UseBasin Endpoint', name: 'usebasin', widget: 'string' }
              - { label: 'Google Map', name: 'googlemap', widget: 'string' }
              - { label: 'Tag Manager ID', name: 'gtm', widget: 'string' }
              - label: "Social Media"
                name: "social"
                widget: "object"
                fields:
                  - { label: 'Facebook', name: 'facebook', widget: 'string', default: "#" }
                  - { label: 'Twitter', name: 'twitter', widget: 'string', default: "#" }
                  - { label: 'Pinterest', name: 'pinterest', widget: 'string', default: "#" }
                  - { label: 'Instagram', name: 'instagram', widget: 'string', default: "#" }
                  - { label: 'LinkedIn', name: 'linkedin', widget: 'string', default: "#" }
              - label: "Schema Info"
                name: "schema"
                widget: "object"
                fields:
                  - { label: 'type', name: 'type', widget: 'string' }
                  - { label: 'priceRange', name: 'priceRange', widget: 'string' }
                  - { label: 'Reservation', name: 'reservation', widget: 'boolean', required: false }
                  - { label: 'Opening Hours', name: 'openinghour', widget: 'string' }
                  - { label: 'Logo in Footer', name: 'logofooter', widget: 'image' }
                  - { label: 'Logo', name: 'logo', widget: 'image' }
                  - { label: 'OpenGraph Image', name: 'ogimage', widget: 'image' }
                  - { label: 'Show Address Publicly?', name: 'address_toggle', widget: 'boolean', required: false }
                  - { label: 'Address Line 1', name: 'address1', widget: 'string' }
                  - { label: 'Address Line 2', name: 'address2', widget: 'string' }
                  - { label: 'City', name: 'city', widget: 'string' }
                  - { label: 'Region', name: 'region', widget: 'string' }
                  - { label: 'Postal Code', name: 'postalcode', widget: 'string' }
                  - { label: 'Country', name: 'country', widget: 'string' }
                  - { label: 'Phone Number', name: 'phone', widget: 'string', default: "+1-" }
                  - { label: 'Email Address', name: 'email', widget: 'string' }
              - label: "Business Hours"
                name: "hours"
                widget: list
                fields:
                  - { label: 'Enter Hour', name: 'hours', widget: 'string' }

  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "_index"
        file: "content/_index.md"
        fields:
          - { label: "SEO Title Max 45 characters", name: "title", widget: "string" }
          - { label: "SEO Description Max 120 characters", name: "description", widget: "string" }
          - { label: "Hero Img", name: "heroimg", widget: "image" }
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Desc", name: "hero_desc", widget: "text" }
          - { label: "Hero CTA", name: "hero_cta", widget: "string" }
          - { label: "About Description", name: "about_desc", widget: "text" }
          - { label: "About Img", name: "aboutimg", widget: "image" }
          - { label: "Book Description", name: "book_desc", widget: "text" }
          - { label: "Book Img", name: "bookimg", widget: "image" }
          - { label: "Free Chapter Description", name: "free_chapter_desc", widget: "text" }
          - { label: "Free Chapter Img", name: "free_chapter_img", widget: "image" }
          - { label: "Free Chapter CTA", name: "free_chapter_cta", widget: "string" }

        